name: Build and Test MCP Servers

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    # Steps to build Docker image and test endpoints
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install Docker
      run: |
        sudo apt-get update
        sudo apt-get install -y docker.io
        docker --version

    - name: Build Docker image
      run: |
        docker build -t mcpo .

    - name: Run Docker container
      run: |
        docker run -d --name mcpo_server -p 8000:8000 mcpo

    - name: Install testing dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests pytest

    - name: Run Endpoint Tests
      run: |
        pytest tests/endpoints_test.py
